### ISSUE TITLE
apm32f103vb cdc枚举失败

### ISSUE THREAD

**Issue by blimjoe** [CherryUSB/cherryusb_apm32#1]
sakumisu，你好。在实验时遇到了下面的问题。
运行在rtthread上，apm32f103vb-mini硬件，参考https://cherryusb.readthedocs.io/zh-cn/latest/quick_start/rt-thread/rtthread.html做的。cherryusb使用的是这个repo中的内容。
在运行时，上位机linux枚举失败，rttthread中的log没有进入到msh >。
上位机linux dmesg看到枚举失败。
这个是我的main
`#include <rtthread.h>
#include <rtdevice.h>
#include <board.h>

#include <apm32f10x.h>
#include <apm32f10x_misc.h>
#include <apm32f10x_eint.h>

extern void cdc_acm_init(void);

int main(void) {
	cdc_acm_init();
	while(1) {
		rt_kprintf("alive\n");
		rt_thread_mdelay(500);
	}
}

void USBD2_Disable() {
	USBD->SWITCH = BIT_RESET;
}
	
void usb_dc_low_level_init(void) {
	  EINT_Config_T EINT_ConfigStruct;
    
    RCM_ConfigUSBCLK(RCM_USB_DIV_1_5);
    RCM_EnableAPB1PeriphClock(RCM_APB1_PERIPH_USB);
    
    EINT_ConfigStruct.mode = EINT_MODE_INTERRUPT;
    EINT_ConfigStruct.line = EINT_LINE_18;
    EINT_ConfigStruct.trigger = EINT_TRIGGER_RISING;
    EINT_ConfigStruct.lineCmd = ENABLE;
    EINT_Config(&EINT_ConfigStruct);
    
#if USB_SELECT == USB1
    NVIC_EnableIRQRequest(USBD1_LP_CAN1_RX0_IRQn, 2, 0);  
#else
    NVIC_EnableIRQRequest(USBD2_LP_CAN2_RX0_IRQn, 2, 0);
#endif    
    NVIC_EnableIRQRequest(USBDWakeUp_IRQn, 1, 0);  
    
#if USB_SELECT == USB1
	  USBD2_Disable();
    
#else
    USBD2_Enable();
#endif
    
}

void usb_dc_low_level_deinit(void)
{    
#if USB_SELECT == USB1
    NVIC_DisableIRQRequest(USBD1_LP_CAN1_RX0_IRQn);
#else
    NVIC_DisableIRQRequest(USBD2_LP_CAN2_RX0_IRQn);
#endif    
    NVIC_DisableIRQRequest(USBDWakeUp_IRQn);
}`

**Comment by blimjoe** [comment]
查到usb_dc_fsdev.c中
    winterruptmask = USB_CNTR_CTRM | USB_CNTR_WKUPM |
                     USB_CNTR_SUSPM | USB_CNTR_ERRM |
                     USB_CNTR_SOFM | USB_CNTR_ESOFM |
                     USB_CNTR_RESETM;
		
    /* Set interrupt mask */
    USB->CNTR = (uint16_t)winterruptmask;
    
CNTR寄存器已设置，就出错了
uart的中断也像是失效了

**Comment by sakumisu** [comment]
这些自行解决把，不在维护
